// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "kq;xw2PiBtj==O9}+EJz":
            case "spaceship":return img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
...............c................
..............ccc...............
.............b9b9b..............
.............b9b9b..............
..........bbbbbbbbbbb...........
.........bbbbcccccbbbb..........
........bbbbbcccccbbbbb.........
.......bbbbbaacccaabbbbb........
.......bbbb..accca..bbbb........
.......bbb...accca...bbb........
.......bb....accca....bb........
.......b...bbcccccbb...b........
...........bbbcccbbb............
...........bb.282.bb............
...........b..424..b............
..............545...............
..............555...............
...............5................
................................
`;
            case "}i8HAmYf|JWv[2$*S7Dl":
            case "Spaceship 3":return img`
................................
................................
................................
................................
................................
................................
................................
................................
..............66666.............
.............6c999c6............
...........6.6ccccc6.6..........
..........6c.cccaccc.c6.........
..........6c.ccaaacc.c6.........
.........6bcaccacaccacb6........
........6bbcacacccacacbb6.......
.......6bbbcacacccacacbbb6......
.......6bdbcaaacccaaacbdb6......
......6bdbbcccacccacccbbdb6.....
......6bbbbbbbccaccbbbbbbb6.....
.....6bbbdbb66cacac66bbdbbb6....
.....6bbdb66.6accca6.66bdbb6....
.....6bd66...6accca6...66db6....
......66.....6accca6.....66.....
............66accca66...........
...........6bbcccccbb6..........
...........6bbbcccbbb6..........
...........6bb62826bb6..........
...........6b6.424.6b6..........
............6..545..6...........
...............555..............
................5...............
................................
`;
            case "AY!95%":
            case "Asteroid 1":return img`
. . . . . . . . . c c 8 . . . . 
. . . . . . 8 c c c f 8 c c . . 
. . . c c 8 8 f c a f f f c c . 
. . c c c f f f c a a f f c c c 
8 c c c f f f f c c a a c 8 c c 
c c c b f f f 8 a c c a a a c c 
c a a b b 8 a b c c c c c c c c 
a f c a a b b a c c c c c f f c 
a 8 f c a a c c a c a c f f f c 
c a 8 a a c c c c a a f f f 8 a 
. a c a a c f f a a b 8 f f c a 
. . c c b a f f f a b b c c 6 c 
. . . c b b a f f 6 6 a b 6 c . 
. . . c c b b b 6 6 a c c c c . 
. . . . c c a b b c c c . . . . 
. . . . . c c c c c c . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
